<a href="https://colab.research.google.com/github/shivasai-max/MOVIE_RECOMMENDATION_SYSTEM_ALGONIVE/blob/main/MOVIE_RECOMMENDATION_SYSTEM_ALGONIVE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

DATA COLLECTION AND PRE_PROCESSING

In [ ]:
# Loading the data from the csv file to a pandas dataframe
movies_data = pd.read_csv('/content/movie.csv')

In [ ]:
ratings_data = pd.read_csv('/content/rating.csv')

In [ ]:
movies_data.columns

Index(['movieId', 'title', 'genres'], dtype='object')

In [ ]:
# Printing the first 5 rows of the dataframe
movies_data.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy


In [ ]:
#number of rows and columns in the dataset
movies_data.shape

(27278, 3)

In [ ]:
# selecting the relevant features for recommendation
selected_features = ['title','genres']
print(selected_features)


['title', 'genres']


In [ ]:
# Replacing the null values with null string
for feature in selected_features:
 movies_data['genres'] = movies_data['genres'].fillna('')
 movies_data['title'] = movies_data['title'].fillna('')


In [ ]:
combined_features = movies_data['genres'] + ' ' + movies_data['title']

In [ ]:
print(combined_features)

0        Adventure|Animation|Children|Comedy|Fantasy To...
1                Adventure|Children|Fantasy Jumanji (1995)
2                   Comedy|Romance Grumpier Old Men (1995)
3            Comedy|Drama|Romance Waiting to Exhale (1995)
4                Comedy Father of the Bride Part II (1995)
                               ...                        
27273                  Comedy Kein Bund für's Leben (2007)
27274                 Comedy Feuer, Eis & Dosenbier (2002)
27275                         Adventure The Pirates (2014)
27276               (no genres listed) Rentun Ruusu (2001)
27277            Adventure|Fantasy|Horror Innocence (2014)
Length: 27278, dtype: object


In [ ]:
# Converting the text data to feature vectors(numerical Values)
vectorizer = TfidfVectorizer()


In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 175689 stored elements and shape (27278, 21962)>
  Coords	Values
  (0, 517)	0.24536580772582445
  (0, 991)	0.3039951743939661
  (0, 3668)	0.2929512624851328
  (0, 4081)	0.15494721902754352
  (0, 6592)	0.2814072916113002
  (0, 19762)	0.6044911641488271
  (0, 18523)	0.4051187234742243
  (0, 156)	0.35893266785406525
  (1, 517)	0.2567787754408913
  (1, 3668)	0.306577624413144
  (1, 6592)	0.2944966962178824
  (1, 156)	0.3756280949311694
  (1, 10084)	0.782464089212663
  (2, 4081)	0.140032877221065
  (2, 156)	0.3243838419539685
  (2, 16389)	0.18541606743135183
  (2, 8126)	0.6757181128752536
  (2, 13932)	0.47027587325402365
  (2, 12380)	0.4037727495536775
  (3, 4081)	0.1397825672273599
  (3, 156)	0.32380400299722584
  (3, 16389)	0.1850846345879182
  (3, 5625)	0.10994179476585171
  (3, 20968)	0.5336406454610856
  (3, 19590)	0.2992187341842305
  :	:
  (27273, 7394)	0.46978576614172624
  (27273, 11158)	0.442464454757178
  (27273, 174)	

COSINE SIMILARITY

In [ ]:
#getting the similarity score using cosine similarity
similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1.         0.37051575 0.13812966 ... 0.08185539 0.         0.16806805]
 [0.37051575 1.         0.12184768 ... 0.08566282 0.         0.17588558]
 [0.13812966 0.12184768 1.         ... 0.         0.         0.        ]
 ...
 [0.08185539 0.08566282 0.         ... 1.         0.         0.27433577]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.16806805 0.17588558 0.         ... 0.27433577 0.         1.        ]]


In [ ]:
print(similarity.shape)

(27278, 27278)


In [ ]:
# getting the movie name by the user
movie_name = input('Enter the Movie Name:')

Enter the Movie Name:Toy Story (1995)


In [ ]:
#creating a list with all the movie names given in the dataset

list_of_all_titles = movies_data['title'].tolist()
for movie in list_of_all_titles:
    print(movie)

Toy Story (1995)
Jumanji (1995)
Grumpier Old Men (1995)
Waiting to Exhale (1995)
Father of the Bride Part II (1995)
Heat (1995)
Sabrina (1995)
Tom and Huck (1995)
Sudden Death (1995)
GoldenEye (1995)
American President, The (1995)
Dracula: Dead and Loving It (1995)
Balto (1995)
Nixon (1995)
Cutthroat Island (1995)
Casino (1995)
Sense and Sensibility (1995)
Four Rooms (1995)
Ace Ventura: When Nature Calls (1995)
Money Train (1995)
Get Shorty (1995)
Copycat (1995)
Assassins (1995)
Powder (1995)
Leaving Las Vegas (1995)
Othello (1995)
Now and Then (1995)
Persuasion (1995)
City of Lost Children, The (Cité des enfants perdus, La) (1995)
Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)
Dangerous Minds (1995)
Twelve Monkeys (a.k.a. 12 Monkeys) (1995)
Wings of Courage (1995)
Babe (1995)
Carrington (1995)
Dead Man Walking (1995)
Across the Sea of Time (1995)
It Takes Two (1995)
Clueless (1995)
Cry, the Beloved Country (1995)
Richard III (1995)
Dead Presidents (1995)
Restoration (1995)
Morta

In [ ]:
#finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

['Toy Story (1995)', 'Toy Story 2 (1999)', 'Tommy Boy (1995)']


In [ ]:
close_match = find_close_match[0]
print(close_match)

Toy Story (1995)


In [ ]:
# Find the index of the movie with title
index_of_the_movie = movies_data[movies_data['title'] == close_match].index[0]
print(index_of_the_movie)

0


In [ ]:
#getting the list of similar movies
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)


[(0, np.float64(1.0000000000000002)), (1, np.float64(0.37051574567016066)), (2, np.float64(0.13812966269911886)), (3, np.float64(0.13788275471803008)), (4, np.float64(0.13899385769577233)), (5, np.float64(0.16481524455511792)), (6, np.float64(0.18117140632595538)), (7, np.float64(0.2510122427261337)), (8, np.float64(0.1425178801672656)), (9, np.float64(0.20666277398189126)), (10, np.float64(0.1705051514428617)), (11, np.float64(0.13081876750534221)), (12, np.float64(0.39061489818796546)), (13, np.float64(0.16952972157645851)), (14, np.float64(0.1814691880223336)), (15, np.float64(0.16394156059296427)), (16, np.float64(0.11741684249551058)), (17, np.float64(0.16363823479964754)), (18, np.float64(0.10381235968790536)), (19, np.float64(0.1645103996522508)), (20, np.float64(0.14830498399989456)), (21, np.float64(0.13363757649214678)), (22, np.float64(0.15828775488442123)), (23, np.float64(0.15037372480054956)), (24, np.float64(0.11046869804503474)), (25, np.float64(0.16743345936900847)), (

In [ ]:
len(similarity_score)

27278

In [ ]:
sorted_similar_movies = sorted(similarity_score,key = lambda x:x[1], reverse=True)
print(sorted_similar_movies)

[(0, np.float64(1.0000000000000002)), (3027, np.float64(0.8742364441555871)), (15401, np.float64(0.8144714285535753)), (21981, np.float64(0.6809295239484658)), (24460, np.float64(0.5794264152382212)), (24458, np.float64(0.5759513873743092)), (25463, np.float64(0.5453684485966134)), (19186, np.float64(0.5255096708577932)), (4833, np.float64(0.5116096346306515)), (25461, np.float64(0.48430685020474673)), (15773, np.float64(0.46467902352596246)), (10987, np.float64(0.41132982843928784)), (12, np.float64(0.39061489818796546)), (2077, np.float64(0.37681308836907934)), (5744, np.float64(0.3750427577661087)), (1, np.float64(0.37051574567016066)), (19997, np.float64(0.3589290113037516)), (3312, np.float64(0.357329618023716)), (21355, np.float64(0.35568447094006705)), (4211, np.float64(0.3538941972039809)), (9707, np.float64(0.3512549026119364)), (24092, np.float64(0.349659796673096)), (27189, np.float64(0.3491771841150612)), (7814, np.float64(0.34615039875672227)), (124, np.float64(0.345802937

In [ ]:
#print the name of similar movies based on the index
print('Movies Suggested for You: \n')
i=1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i,'.',title_from_index)
    i+=1

Movies Suggested for You: 

1 . Toy Story (1995)
2 . Toy Story 2 (1999)
3 . Toy Story 3 (2010)
4 . Toy Story of Terror (2013)
5 . Toy Story Toons: Small Fry (2011)
6 . Toy Story Toons: Hawaiian Vacation (2011)
7 . Toy Story That Time Forgot (2014)
8 . Tin Toy (1988)
9 . Toy, The (1982)
10 . Toy Story Toons: Partysaurus Rex (2012)
11 . Christmas Toy, The (1986)
12 . Wild, The (2006)
13 . Balto (1995)
14 . NeverEnding Story, The (1984)
15 . Toy Soldiers (1991)
16 . Jumanji (1995)
17 . Christmas Story 2, A (2012)
18 . We're Back! A Dinosaur's Story (1993)
19 . Turbo (2013)
20 . Shrek (2001)
21 . Magic in the Water (1995)
22 . Aladdin (1992)
23 . The Beautiful Story (1992)
24 . Chipmunk Adventure, The (1987)
25 . NeverEnding Story III, The (1994)
26 . Valiant (2005)
27 . Tall Tale (1995)
28 . Enchanted (2007)
29 . Gordy (1995)


MOVIE RECOMMENDATION SYSTEM

In [ ]:
movie_name = input('Enter the Movie Name:')
list_of_all_titles = movies_data['title'].tolist()
find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)
close_match = find_close_match[0]
index_of_the_movie = movies_data[movies_data['title'] == close_match].index[0]
similarity_score = list(enumerate(similarity[index_of_the_movie]))
sorted_similar_movies = sorted(similarity_score,key = lambda x:x[1], reverse=True)
print('Movies Suggested for You: \n')
i=1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<11):
    print(i,'.',title_from_index)
    i+=1

Enter the Movie Name:Jumanji (1995)
Movies Suggested for You: 

1 . Jumanji (1995)
2 . Toy Story (1995)
3 . Magic in the Water (1995)
4 . Tall Tale (1995)
5 . Casper (1995)
6 . Napoleon (1995)
7 . Gordy (1995)
8 . Pan (1995)
9 . Amazing Panda Adventure, The (1995)
10 . Five Children and It (2004)


In [ ]:
import gradio as gr
import difflib

def recommend_ui(movie_name):
    list_of_all_titles = movies_data['title'].tolist()
    find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

    if not find_close_match:
        return "❌ No similar movie found. Please check the spelling."

    close_match = find_close_match[0]
    index_of_the_movie = movies_data[movies_data['title'] == close_match].index[0]
    similarity_score = list(enumerate(similarity[index_of_the_movie]))
    sorted_similar_movies = sorted(similarity_score, key=lambda x: x[1], reverse=True)

    result = f"🎬 Movies Suggested for You (Based on '{close_match}'):\n\n"
    i = 1
    for movie in sorted_similar_movies:
        index = movie[0]
        title_from_index = movies_data[movies_data.index == index]['title'].values[0]
        if i < 11:
            result += f"{i}. {title_from_index}\n"
            i += 1

    return result


In [ ]:
interface = gr.Interface(
    fn=recommend_ui,
    inputs=gr.Textbox(lines=1, placeholder="Enter Movie Name"),
    outputs=gr.Textbox(lines=15, label="Recommended Movies"),
    title="🎥 Movie Recommendation System - BY Shiva Sai (ALGONIVE)",
    description="Type any movie name and get similar movies based on content matching.",
)

interface.launch()


It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://81627ef149b16226e2.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
